### ISSUE TITLE
[question] IlmImf library

### ISSUE THREAD

**Issue by memsharded** [Mikayex/conan-ilmbase#4]
Hi!

I am trying to package OpenCV which has a dependency to ``IlmImf`` library, from OpenEXR. The OpenCV distribution has it internal to the repo, but I would like to use an external conan package for it, as I already did for the other dependencies: libjpeg, libtiff, etc.

I have had a look to their site: http://www.openexr.com/, but it is not clear to me which library is this one. Do you have any idea?

Many thanks!

**Comment by Mikayex** [comment]
`IlmImf` is an utility library used as a dependency of OpenEXR. In fact, I started to create a conan recipe for OpenEXR a long time ago but I didn't had time to finish it (and update it to conan 1.X) : https://github.com/Mikayex/conan-openexr

If you want, you can submit a pull request there, I'll merge it.
I'm really interested in an OpenCV package, with all available compilation options and opencv_contrib repo too.

**Comment by memsharded** [comment]
Thanks! Still not clear, you said it is an utility library used as a dependency of OpenEXR, doesn't it imply that it should be in a separate package? Like OpenEXR => IlmImf => IlmBase?

Current effort for OpenCV is: https://github.com/conan-community/conan-opencv. The plan is:
- First basic OpenCV 2.4, built with external dependencies instead of the "3rdparty" folder, in Win, Linux, Mac.
- Generalize that version to using the available compilation options
- Investigate OpenCV 3, and how to manage the "contrib" repo. Actually I'd love to be able to build contrib depending on OpenCV, and not simultaneously, but for that we probably need some help and advise from OpenCV maintainers.

**Comment by Mikayex** [comment]
Oh, sorry I mixed up `IlmImf` and `IlmBase`... I thought you ask about the later.
So, after seeing the library again : `IlmImf` *is* the OpenEXR library (maybe its legacy name...).

To summarize :
- OpenEXR == `IlmImf`
- `IlmImf` depends on `IlmBase` (this package)

**Comment by memsharded** [comment]
Thanks for the info!

This is a bit unfortunate in some sense, as OpenCV is using the IlmImf library explictly, not OpenEXR, not sure if a replacement will work. I'll try to check when possible.
